spring.application.name=movie-recommender-backend

# MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/movie_recommender}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=${PORT:8080}

# ML Service
ml.service.base-url=${ML_SERVICE_BASE_URL:http://127.0.0.1:8000}